version: "3"

services: 
  altair:
    build:
      context: .
      dockerfile: development.Dockerfile
    command: ./wait-for-it.sh db:27017 -- npm run start-debug-brk
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - db
    env_file: 
      - .env
    environment:
      - DB_HOST=db
    volumes:
      - .:/usr/local/src
      - /usr/local/src/node_modules

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
